apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-platform-frontend-deployment
  namespace: recipe-platform-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe-platform-frontend
  template:
    metadata:
      labels:
        app: recipe-platform-frontend
    spec:
      containers:
        - name: recipe-platform-frontend-container
          image: leonnura/frontendrecipe:$(Build.BuildId)
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-platform-frontend-service
  namespace: recipe-platform-namespace
spec:
  selector:
    app: recipe-platform-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
