apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-sharing-platform-back-deployment
  namespace: recipe-platform-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe-sharing-platform-back
  template:
    metadata:
      labels:
        app: recipe-sharing-platform-back
    spec:
      containers:
        - name: recipe-sharing-platform-back-container
          image: leonnura/backend-recipe:$(Build.BuildId)
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-sharing-platform-back-service
  namespace: recipe-platform-namespace
spec:
  selector:
    app: recipe-sharing-platform-back
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
