apiVersion: v1
kind: ServiceAccount
metadata:
  name: real-estate-listing-service-account
  namespace: real-estate-listing-namespace

---
# Create a role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: real-estate-listing-role
  namespace: real-estate-listing-namespace
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
# Create a role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: real-estate-listing-role-binding
  namespace: real-estate-listing-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: real-estate-listing-role
subjects:
  - kind: ServiceAccount
    name: real-estate-listing-service-account
    namespace: real-estate-listing-namespace

---
# Create a secret for the service account
apiVersion: v1
kind: Secret
metadata:
  name: real-estate-listing-service-account-token
  namespace: real-estate-listing-namespace
  annotations:
    kubernetes.io/service-account.name: real-estate-listing-service-account
type: kubernetes.io/service-account-token
