apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: real-estate-listing-namespace
type: Opaque
data:
  POSTGRES_DB: cmVhbC1lc3RhdGUtcGxhdGZvcm0= # "real-estate-platform"
  POSTGRES_USER: cmVhbC1lc3RhdGUtcGxhdGZvcm0tdXNlcg== # "real-estate-platform-user"
  POSTGRES_PASSWORD: R1JodHgzckM= # "GRhtx3rC"

{
  "ConnectionStrings": {
    "DefaultConnection": "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
  }
}
